version: "3.4"
services:
  ml:
    image: mlinsectacr.azurecr.io/cocomcheck-your-insect-ml:v1
    container_name: insectid-mlmodel
    cap_drop:
      - SYS_ADMIN
    networks:
      - secure-network

  backend:
    image: mlinsectacr.azurecr.io/cocomcheck-your-insect-backend:v1
    container_name: insectid-apicontainer
    ports:
      - 7089:80
    depends_on:
      - ml
    cap_drop:
      - SYS_ADMIN
    networks:
      - secure-network

  frontend:
    image: mlinsectacr.azurecr.io/cocomcheck-your-insect-frontend:v1
    container_name: insectid-frontendcontainer
    ports:
      - 8080:80
    cap_drop:
      - SYS_ADMIN
    networks:
      - secure-network

networks:
  secure-network:
    driver: bridge
